### PR TITLE
Test results from Colibrio Reader Framework 👍

### PR DESCRIPTION
**Pull request by larscwallin**

### CODE REVIEW

**Comment by iherman** [comment]
@larscwallin this looks great to me. One cosmetic issue: the `$description` field in the test report suite are used as a description of the implementation; see, for example, [1]. I wonder whether it is possible to use a somewhat more informative description (not too long, though:-). To give more information on what this implementation is; this is what the reviewers will see first!

B.t.w. @marisademeglio, this would be a useful update for your implementation, too!

[1] https://w3c.github.io/publ-tests/test_reports/manifest_processing/#section_1.1

**Review by mattgarrish — APPROVED** [review]
Nothing more to add to Ivan's comments from me.

**Comment by wareid** [comment]
I'll second @iherman's comments, but otherwise looks good to me!

**Review by wareid — APPROVED** [review]

**Comment by larscwallin** [comment]
Thanks for reviewing! I have now pushed a new and more descriptive version :)

**Review by iherman — APPROVED** [review]

**Pull request merged**
