### PR TITLE
Update los.json

### PR DESCRIPTION
**Pull request by GarthConboy**
readingOrder should be an array, get the valued enclosed in "[ ... ]".

### CODE REVIEW

**Comment by GarthConboy** [comment]
Assuming this is agreed, I'll also update the LPF version.

**Comment by mattgarrish** [comment]
Since this isn't testing the conversion of a manifest, seems fine to me (technically the reading system has to convert a single string/object when found; there's no recommended form).

**Review by mattgarrish — APPROVED** [review]

**Comment by GarthConboy** [comment]
Thanks for the approval Matt.  But, I'm going to abandon the PR, as this single object specification should be legal (as you said), and is probably worth having in one of our test files.

**Comment by GarthConboy** [comment]
The "bug" I was fixing was really a bug; likely good to leave this single object (non-array) readingOrder in one of our test files.

**Pull request closed without merging**
