### PR TITLE
Garth conboy add play books test results

### PR DESCRIPTION
**Pull request by GarthConboy**
Add initial Play Books test results.

### CODE REVIEW

**Comment by wareid** [comment]
@GarthConboy can you update the $description field to be more descriptive? I believe this is what is used to populate that top section of the manifest test results page. Otherwise, looks awesome!

**Comment by GarthConboy** [comment]
Hi Wendy.  The other three $descriptions are:

    "$description" : "Test implementation of the processing algorithm in JavaScript.",
    "$description" : "Test implementation of the processing algorithm in Typescript.",
    "$description": "Audiobooks parser",

I updated mine to be:

    "$description" : "Test implementation from Google Play Books ingest pipeline Unit Tests.",

Acceptable?

(and, sorry Wendy, I should have explicitly added you as a reviewer the first time 'round! :-)

**Comment by mattgarrish** [comment]
@iherman has updated his description to:

> Implementation in Typescript that was used to debug the processing algorithm while specifying it. Not a reading system per se, although could be used as part of an implementation.

https://w3c.github.io/publ-tests/test_reports/manifest_processing/index.html#publ_manifest_implementations

I have to do something similar for the manifest2internal one I did to disambiguate it from the real world implementations.

I imagine what we want would be something like "Google Play Books - Results from implementing an audiobook processor in the content ingestion pipeline ..." (But worded to make sense to what you've actually done, of course.)

**Comment by GarthConboy** [comment]
I'm also happy to commit for now, and have me/others tune text later when we have a plan. :-)

For now, switched to Ivan's suggested text, as it was accurate.

**Review by wareid — APPROVED** [review]

**Pull request merged**
