### PR TITLE
Thorium Reader test results

### PR DESCRIPTION
**Pull request by llemeurfr**
This is the result of tests applied to Thorium Reader. It includes generic manifest processing, audiobook specific manifest processing, audiobook UA behaviors, LPF package processing. 

The first shot applies to Thorium 1.3, release in June 2020. 
In the coming days, other commits will be done, related to updates on W3C pub manifest handling (entry page, html TOC, case insensitive handling of rel values).

### CODE REVIEW

**Comment by iherman** [comment]
Wonderful! Thanks a lot @llemeurfr 

I have made a PR _against this branch_ in https://github.com/w3c/publ-tests/pull/54 to add the LPF reporting. Otherwise, I checked out this branch on my own machine and, as far as I could see, the reporting with the ThoriumReader works fine. The report surely looks greater with that implementation added :-)

**Comment by llemeurfr** [comment]
The codebase of Thorium Reader has evolved so that PEP and TOC are handled, and `rel` values in mixed case also.  
Most test are now green. 
About a4.2.05, this test is problematic, see #55. 
About m6.07, the requirement to have the URL of the PEP in manifest resources should IMO be suppressed (see https://github.com/w3c/audiobooks/issues/75) and therefore this test should also be suppressed.

**Comment by llemeurfr** [comment]
The resulting v1.5 will be deployed on early October.

**Comment by iherman** [comment]
Thanks @llemeurfr, thorium is now part of the official report!

**Pull request merged**
